#
# Makefile for the kernel multimedia device drivers.
#
obj-$(CONFIG_SIANO1130_CONTROL)	+= SIANO1130_app.o src/ ts_processor.o Platforms/
#obj-y        := include/ include_internal/ platforms/ src/
EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/SIANO_SMS1130/src/ -Idrivers/media/dvb/rkdtv/SIANO_SMS1130/include/ -Idrivers/media/dvb/rkdtv/SIANO_SMS1130/include_internal/ -Idrivers/media/dvb/rkdtv/SIANO_SMS1130/include_internal/Include/ -Idrivers/media/dvb/rkdtv/SIANO_SMS1130/Platforms/ -Idrivers/media/dvb/rkdtv/SIANO_SMS1130/Platforms/RKOS/ -Idrivers/media/dvb/rkdtv/SIANO_SMS1130/
