#
# Makefile for the kernel multimedia device drivers.
#
obj-$(CONFIG_DIBCOM7090_CONTROL)	+= dibx000_i2c_common.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/DIBCom7090/include/
