obj-$(CONFIG_GX1131_CONTROL)	+= av2011.o GX1131.o rda5812.o Sharp7306.o Stv6110A.o zl10037.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/ -Idrivers/media/dvb/rkdtv/GX1131/ -Idrivers/media/dvb/rkdtv/GX1131/GX1131_Driver_V1.6/
