#
# Makefile for the kernel multimedia device drivers.
#
obj-$(CONFIG_DIBCOM8096_CONTROL)	+= dib8090p.o dibx090p_ctrl.o 

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/DIBCom8096/include/
