#
# Makefile for the kernel multimedia device drivers.
#
obj-$(CONFIG_GX1131_CONTROL)	+= GX1131_Driver_V1.6/ GX1131_i2c_app.o GX1131_app.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/ -Idrivers/media/dvb/rkdtv/GX1131/ -Idrivers/media/dvb/rkdtv/GX1131/GX1131_Driver_V1.6/

