#
# Makefile for the kernel multimedia device drivers.
#
obj-$(CONFIG_MTV818_CONTROL)	+= MTV818_1.2.0_API/ mtv818_i2c_app.o mtv818_app.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/ -Idrivers/media/dvb/rkdtv/MTV818/ -Idrivers/media/dvb/rkdtv/MTV818/MTV818_1.2.0_API/include/

