obj-$(CONFIG_NMI310_CONTROL)	+= common/ NMI310_app.o I2C_Driver/

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/NMI310_Driver/I2C_Driver/ -Idrivers/media/dvb/rkdtv/NMI310_Driver/inc/ -Idrivers/media/dvb/rkdtv/NMI310_Driver/common/
