#
# Makefile for the kernel multimedia device drivers.
#
obj-$(CONFIG_GX1001_CONTROL)	+= RF_TDA18250.o tmbslTDA18250A.o tmbslTDA18250A_Advanced.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/ -Idrivers/media/dvb/rkdtv/GX1001/ -Idrivers/media/dvb/rkdtv/GX1001/tda18250/

