#
# Makefile for the kernel multimedia device drivers.
#
obj-$(CONFIG_DIBCOM7090_CONTROL)	+= dib7000p.o dib7000p_gpio.o dib7000p_io.o dib7000p_monitor.o dib7000p_power.o dib7000p_tune.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/DIBCom7090/include/
