obj-$(CONFIG_NMI320_CONTROL)	+= common/ NMI320_app.o I2C_Driver/

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/NMI320_Driver/I2C_Driver/ -Idrivers/media/dvb/rkdtv/NMI320_Driver/inc/ -Idrivers/media/dvb/rkdtv/NMI320_Driver/common/
