#
# Makefile for the touchscreen drivers.
#
# Each configuration option enables a list of files.


obj-$(CONFIG_RK_REMOTECTL_GPIO)     += rkxx_remotectl.o
obj-$(CONFIG_RK_REMOTECTL_PWM)      += rk_pwm_remotectl.o
