#obj-$(CONFIG_SIANO1130_CONTROL)	+=  SmsHostlibLiteCmmb.o SmsHostLibLiteCommon.o SmsHostlibLiteMs.o
obj-$(CONFIG_SIANO1130_CONTROL)	+= SmsHostLibLiteCommon.o SmsHostlibLiteMs.o
EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends
