#
# Makefile for the kernel multimedia device drivers.
#
obj-$(CONFIG_MTV818_CONTROL)	+= raontv.o raontv_isdbt.o raontv_rf.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/MTV818/MTV818_1.2.0_API/include/ -Idrivers/media/dvb/rkdtv/MTV818/MTV818_1.2.0_API/oem/
