#
# Makefile for the kernel multimedia device drivers.
#
obj-$(CONFIG_DIBCOM8096_CONTROL)	+= dib8000p.o dib8000p_gpio.o dib8000p_io.o dib8000p_monitor.o dib8000p_power.o dib8000p_tune.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core/  -Idrivers/media/dvb/frontends -Idrivers/media/dvb/rkdtv/DIBCom8096/include/
